id = "poweron"
name = "PowerOn"
version = "0.0.1"
schema_version = 1
authors = ["kusuki00z <https://github.com/kusuki00Z>"]
description = "This is a Zed extension used for the PowerOn language syntax highlighting"
repository = "https://github.com/kusuki00Z/zed-poweron-extension"

[grammars.poweron]
repository = "file:///C:/Users/rzhou/dev/git%20backup/zed-poweron-extension"
rev = "ba92e0b2a26d1c348fa7eba1be5eef698d599dca"
