id = "poweron"
name = "PowerOn"
version = "0.1.1"
schema_version = 1
authors = ["kusuki00z <https://github.com/kusuki00Z>"]
description = "Supports PowerOn Syntax Highlighting"
repository = "https://github.com/kusuki00Z/zed-poweron-extension"

[grammars.poweron]
repository = "https://github.com/kusuki00Z/zed-poweron-extension"
rev = "main"
